apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jarta-thought-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jarta
        tier: backend
        track: stable
    spec:
      containers:
        - name: jarta-thought-service
          image: "jarta-thought-service:1.1"
          ports:
            - name: http
              containerPort: 9997
---
kind: Service
apiVersion: v1
metadata:
  name: jarta-thought-service
spec:
  selector:
    app: jarta
    tier: backend
  ports:
    - protocol: TCP
      port: 9997
      targetPort: http